controllers/PaymentController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

use yii\data\ActiveDataProvider;
use Codeception\Test\Unit;
use yii\authclient\InvalidResponseException;
use yii\console\ErrorHandler;
use yii\httpclient\Response;

use app\components\Apiservice;

class PaymentController extends Controller
{

    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    //No Login
                    [
                        'actions' => [
                            'index', 'create', 'get-form-payment', 'verify-send-sms', 'save-verify-send-sms', 'verify-payment', 'get-data-formall', 'check-data-redirect', 'check-data-redirect-qr', 'load-form', 'get-order-id', 'get-button-qr-code',
                        ],
                        'allow' => true,
                        // 'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
    //ปิดการใช้งานตรวจสอบ csrf 
    // public function beforeAction($action)
    // {
    //     $this->enableCsrfValidation = false;
    //     return parent::beforeAction($action);
    // }

    //เข้ารหัสถอดรหัส code_check
    public function encodeCodecheck($txtCode, $flag)
    {
        $arrTranscode = [];
        $txtCodecheck = '';
        $codeCheck = '';
        $message = '';
        $success = false;
        $secretKey = 'buzz^^';
        if (!empty($txtCode) && !empty($flag)) {
            //เข้ารหัสตอนรับเพื่อส่ง SMS (f002115515sfd)
            if ($flag == 'encode') {
                $arrExplode = explode("|", $txtCode);
                if (!empty($arrExplode)) {
                    $method = empty($arrExplode[0]) ? null : $arrExplode[0];
                    $ref_id = empty($arrExplode[1]) ? null : $arrExplode[1];
                    $create_at = empty($arrExplode[2]) ? null : $arrExplode[2];
                    if (!empty($method) && !empty($ref_id) && !empty($create_at)) {
                        $txtCode = $method . '|' . $ref_id . '|' . $create_at;
                        $codeCheck = base64_encode(Yii::$app->security->encryptByKey($txtCode, $secretKey));
                        $success = true;
                    } else {
                        $message = '!ไม่พบสัญลักษณ์ | ในการเข้ารหัส';
                    }
                } else {
                    $message = '!ไม่สามารถเข้ารหัสได้';
                }
                //แปลงรหัสให้เป็นค่า method, ref_id โดยมี | คั่นต้อง explode
            } else if ($flag == 'decode') {
                $keyConvert = Yii::$app->security->decryptByKey(base64_decode($txtCode), $secretKey);
                if (!empty($keyConvert)) {
                    $arrExplode = explode("|", $keyConvert);
                    if (!empty($arrExplode[0]) && $arrExplode[1] && $arrExplode[2]) {
                        $method = empty($arrExplode[0]) ? null : $arrExplode[0];
                        $ref_id = empty($arrExplode[1]) ? null : $arrExplode[1];
                        $created_at = empty($arrExplode[1]) ? null : $arrExplode[1];
                        $success = true;
                    } else {
                        $message = '!ไม่พบสัญลักษณ์ | ในการถอดรหัส';
                    }
                    // JuPayment::find()->where(['medhod' => $arrExplode[0]])->andWhere(['ref_id' => $arrExplode[0]])->one();
                } else {
                    $message = '!ไม่สามารถถอดรหัสได้';
                }
            }
        } else {
            $message = '!Parameter (flag) ไม่มีข้อมูลส่งมา';
        }
        return  $arrTranscode = [
            'success' =>  empty($success) ? null : $success,
            'code_check' => empty($codeCheck) ? null : $codeCheck,
            'method_name' => empty($method) ? null : $method,
            'ref_id' => empty($ref_id) ? null : $ref_id,
            'created_at' => empty($create_at) ? null : $create_at,
            'message' => empty($message) ? null : $message,
        ];
    }
    //ตอนกดปุ่มมาจ่ายเงิน
    //ส่ง SMS
    //http://localhost:8082/buzz_payment/web/payment/verify-send-sms?method=booking&ref_id=159&amount=15000&customer_name=วรากร ประดิษฐกุล&customer_tel=0877924834&merchant_id=001265540001&merchant_name=บริษัท โตโยต้าบัสส์ จํากัด&text_sms=กดเข้าลิ้งค์นี้เพื่อชำระเงินค่าจองรถยนต์.               
    //https://payment.toyotabuzz.com/paymentgateway/web/payment/verify-send-sms?method=booking&ref_id=159&amount=15000&customer_name=วรากร ประดิษฐกุล&customer_tel=0877924834&merchant_id=001265540001&merchant_name=บริษัท โตโยต้าบัสส์ จํากัด&text_sms=กดเข้าลิ้งค์นี้เพื่อชำระเงินค่าจองรถยนต์.               
    public function actionVerifySendSms()
    {
        $this->layout = 'blank';
        $requestUrl = Yii::$app->request->get();
        // $urlPrefix = $requestUrl['text_sms'] . ' https://buzzpower.in.th/buzz_power/frontend/web/payment/payment/verify-payment/';
        $setUrlList = empty($requestUrl['text_sms']) ? null : $requestUrl['text_sms'];
        $setUrl = Yii::$app->params['urlVerifyPayment'];
        $txtCode = '';
        $res = [];
        $res['status'] = false;
        $res['message'] = 'เตือน! เกิดข้อผิดพลาด กรุณาแจ้งผู้ดูแลระบบ';
        // echo '<pre>'; print_r($requestUrl);
        if (!empty($requestUrl)) {
            $res['check_payment'] = $this->checkDataSendSms($requestUrl);
            // echo '<pre>'; print_r($res['check_payment']); exit;
            //ถ้ายังไม่เคยส่ง SMS มาก่อน
            if (!empty($res['check_payment']) && !empty($res['check_payment']['success'])) {
                $res['add_code']['code_check'] = $this->addCodeCheck($requestUrl['method'], $requestUrl['ref_id']); //ชุด 1 รวมตัวแปร method|ref_id|date_current
                $res['add_code']['code_recheck'] = $this->addCodeCheck($requestUrl['merchant_id'], $requestUrl['ref_id']); //ชุด 2 รวมตัวแปร merchant_id|ref_id|date_current
                if (!empty($res['add_code']['code_check']['success']) && $res['add_code']['code_recheck']['success']) {
                    //สร้าง URL
                    $setUrl .= 'codeCheck=' . $res['add_code']['code_check']['add_encode']['code_check'];
                    $setUrl .= '&codeRecheck=' . $res['add_code']['code_recheck']['add_encode']['code_check'];
                    //set ให้ตัวแปร Request เพื่อแสดง | บันทึก
                    $requestUrl['code_check'] = $res['add_code']['code_check']['add_encode']['code_check'];
                    $requestUrl['code_recheck'] = $res['add_code']['code_recheck']['add_encode']['code_check'];
                }
                //เคยส่ง SMS แล้ว
            } else {
                $res['success'] = false;
                $res['message'] = $res['check_payment']['message'];
                $requestUrl['code_check'] = $res['check_payment']['results']['code_check'];
                $requestUrl['code_recheck'] = $res['check_payment']['results']['code_recheck'];
                $requestUrl['text_sms'] = empty($res['check_payment']['results']['text_sms']) ? $requestUrl['text_sms'] : $res['check_payment']['results']['text_sms'];
            }
        }
        return $this->render('_form-verify-send-sms', [
            'resRequest' => $requestUrl,
            'resPayment' => empty($res['check_payment']) ? null : $res['check_payment'],
            'resFullUrl' => empty($setUrl) ? null : $setUrl,
            'resShortUrl' => empty($res['bitly_url']) ? null : $res['bitly_url'],
        ]);
    }

    public  function actionSaveVerifySendSms()
    {
        $request = Yii::$app->request->get();
        $setUrl = '';
        // echo '<pre>';
        // print_r($request);
        $res = [];
        $res['title']  = '';
        $res['message'] = 'กรุณากดปุ่มส่ง SMS อีกครั้ง';
        $res['success'] = false;
        if (!empty($request)) {
            //แปลง URL
            $res['bitly_convert'] = $this->bitlyShorturl($request['link_before_convert']);
            // echo '<pre>';
            // print_r($res['bitly_convert']);
            // exit;
            if (!empty($res['bitly_convert']['success']) && !empty($res['bitly_convert']['link'])) {
                //เอาข้อความที่ส่งมาเพิ่มไปในข้อความ 
                $setUrl = empty($request['text_sms']) ? $res['bitly_convert']['link'] : $request['text_sms'] . ' ' . $res['bitly_convert']['link'];
                //ส่ง SMS
                $res['send_sms'] = $this->sendSMS($request['customer_tel'], $setUrl);
                if ($res['send_sms']['success']) {
                    //บันทึก Paymemt (NodeJs)
                    $request['text_sms'] = empty($setUrl) ? null : $setUrl;
                    $request['created_by'] = 'system';
                    $request['updated_by'] = 'system';
                    $request['bitly_url'] = empty($res['bitly_convert']['link']) ? null : $res['bitly_convert']['link'];
                    $res['save_data'] = Apiservice::sendApiNodeService('payment/save-jupayment-send-sms?' . http_build_query($request));
                    if ($res['save_data']['success']) {
                        $res['success'] = $res['save_data']['success'];
                        $res['title'] = $res['save_data']['title'];
                        $res['message'] = $res['save_data']['message'];
                    } else {
                        $res['message'] = $res['save_data']['message'];
                    }
                    // echo '<pre>';
                    // print_r($res['save_data']);
                    // exit;
                } else {

views/payment/_form-info.php
<style>
    input[type="text"] {
        border-top: none !important;
        border-right: none !important;
        border-left: none !important;
        border-bottom: 1px dotted #2196f3 !important;
        box-shadow: none !important;
        -webkit-box-shadow: none !important;
        -moz-box-shadow: none !important;
        -moz-transition: none !important;
        -webkit-transition: none !important;
    }

    .heading {
        color: #2196f3;
    }

    .control {
        padding-top: 7px;
    }

    .reciept {
        border-top: 5px solid #2196f3;
        -webkit-box-shadow: 0px 5px 21px -2px rgba(0, 0, 0, 0.47);
        -moz-box-shadow: 0px 5px 21px -2px rgba(0, 0, 0, 0.47);
        box-shadow: 0px 5px 21px -2px rgba(0, 0, 0, 0.47);
        margin-top: 10px;
        margin-bottom: 10px;
    }
</style>
<div class="container">
    <div class="reciept">
        <div class="row" style="margin-top:10px;">
            <div class="col-md-8">
                <div class="col-md-3">
                    <img class="media-object img-thumbnail user-img" style="height: 80px;" alt="User Picture" src="http://via.placeholder.com/80x80"></div>
                <div class="col-md-9 text-right">
                    <h4 class="heading">Aspirant English Classess</h4>
                    <h5 class="heading">Hanuman Mandir C.C.Road, Deoria</h5>
                    <h6 class="heading">+91 9455078760</h6>
                </div>
            </div>
            <div class="col-md-4">

                <div class="form-group">
                    <label class="col-md-4 control">Date :</label>
                    <div class="col-md-8">
                        <input id="" name="name" type="text" placeholder="10-May-2017 02:05 pm" class="form-control">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4 control">Reciept No. :</label>
                    <div class="col-md-8">
                        <input id="" name="name" type="text" placeholder="12349" class="form-control">
                    </div>
                </div>

            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-6 control" for="">Section :</label>
                    <div class="col-md-6" style="padding-left:20px;">
                        <span class=""> </span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control" for="">Batch :</label>
                    <div class="col-md-9">
                        <input id="" name="name" type="text" placeholder="Batch" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-3 control" for="name">Recieve Amount :</label>
                    <div class="col-md-9">
                        <input id="name" name="name" type="text" placeholder="Amount" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control" for="name">Cash :</label>
                    <div class="col-md-9">
                        <input id="checkbox2" type="checkbox" checked="" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control" for="name">Cheque :</label>
                    <div class="col-md-9">
                        <input id="checkbox2" type="checkbox" checked="" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control">Bank Transfer :</label>
                    <div class="col-md-9">
                        <input id="checkbox2" type="checkbox" checked="" class="form-control">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-sm-3 control">Bank Name :</label>
                    <div class="col-sm-9">
                        <input id="" name="name" type="text" placeholder="State Bank of India" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control">Cheque No :</label>
                    <div class="col-sm-9">
                        <input id="" name="name" type="text" placeholder="Cheque no" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control">Date :</label>
                    <div class="col-sm-9">
                        <input id="" name="name" type="text" placeholder="Date" class="form-control">
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="col-md-3 control" for="name">Recieved By :</label>
                    <div class="col-md-9">
                        <input id="name" name="name" type="text" placeholder="Authorised Person" class="form-control">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

views/payment/_form-pay-credit.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use yii\helpers\Url;
// app\assets\PaymentAsset::register($this);

// echo '<pre>'; print_r($customerName); 
?>
<?php //header('Access-Control-Allow-Origin: *'); 
?>
<style>
    .mt-50 {
        margin-top: 50px
    }

    .mb-50 {
        margin-bottom: 50px
    }

    @media(max-width:767px) {
        .card {
            width: 90%;
            padding: 1.5rem
        }
    }

    @media(height:1366px) {
        .card {
            width: 90%;
            padding: 8vh
        }
    }

    .active {
        border-bottom: 2px solid black;
        font-weight: bold
    }

    input {
        border: none;
        outline: none;
        font-size: 1rem;
        font-weight: 600;
        color: #000;
        width: 100%;
        min-width: unset;
        background-color: transparent;
        border-color: transparent;
        margin: 0
    }

    form a {
        color: grey;
        text-decoration: none;
        font-size: 0.87rem;
        font-weight: bold
    }

    form a:hover {
        color: grey;
        text-decoration: none
    }

    form .row {
        overflow: hidden
    }

    form .row-1 {
        border: 1px solid rgba(0, 0, 0, 0.137);
        padding: 1.0rem;
        outline: none;
        width: 100%;
        min-width: unset;
        border-radius: 5px;
        background-color: rgba(221, 228, 236, 0.301);
        border-color: rgba(221, 228, 236, 0.459);
        margin: 2vh 0;
        overflow: hidden
    }

    form .row-2 {
        border: none;
        outline: none;
        background-color: transparent;
        margin: 0;
        padding: 0 0.8rem
    }

    form .row .row-2 {
        border: none;
        outline: none;
        background-color: transparent;
        margin: 0;
        padding: 0 0.8rem
    }

    form .row .col-2,
    .col-7,
    .col-3 {
        display: flex;
        align-items: center;
        text-align: center;
        padding: 0 1vh
    }

    form .row .col-2 {
        padding-right: 0
    }

    input:focus::-webkit-input-placeholder {
        color: transparent
    }

    input:focus:-moz-placeholder {
        color: transparent
    }

    input:focus::-moz-placeholder {
        color: transparent
    }

    input:focus:-ms-input-placeholder {
        color: transparent
    }
</style>
<div class="ju-payment-type-form">
    <div class="container">
        <div class="card-body">
            <div class="form-container">
                <div class="form-horizontal">
                    <h3 class="title">Credit Card (โปรดกรอกข้อมูล)</h3>

                    <!-- <div class="form-group">
                            <label for="ccnumber">ชื่อที่แสดงบนบัตร</label>
                            <input type="text" name="username" required class="form-control ">
                        </div>

                        <label for="ccnumber">หมายเลขบัตร</label>
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="0000 0000 0000 0000">
                            <div class="input-group-append">
                                <span class="input-group-text">
                                    <i class="fa fa-credit-card"></i>
                                </span>
                            </div>
                        </div> -->
                    <!-- credit card info-->
                    <!-- <form role="form"> -->
                    <div class="form-group text-center">
                        <ul class="list-inline">
                            <li class="list-inline-item"><i class="text-muted fa fa-cc-visa fa-2x"></i></li>
                            <li class="list-inline-item"><i class="fa fa-cc-mastercard fa-2x"></i></li>
                            <li class="list-inline-item"><i class="fa fa-cc-amex fa-2x"></i></li>
                            <li class="list-inline-item"><i class="fa fa-cc-discover fa-2x"></i></li>
                        </ul>
                    </div>
                    <div class="form-group">
                        <label for="username">
                            <h5>ชื่อบนบัตร</h5>
                        </label>
                        <div type="text" class="form-control" placeholder="" required="" id="card-name"></div>
                    </div>
                    <div class="form-group">
                        <label for="cardNumber">
                            <h5>หมายเลขบัตร</h5>
                        </label>
                        <div class="input-group">
                            <div type="text" class="form-control" placeholder="" required="" id="card-number"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label data-toggle="tooltip">
                            <h5>วันทื่หมดอายุ</h5>
                        </label>
                        <div class="input-group">
                            <div type="text" class="form-control" placeholder="" required="" id="card-expiry">
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label data-toggle="tooltip" title="รหัส CVV 3 หลักที่ด้านหลังบัตร">
                            <h5>CVV <i class="fa fa-question-circle d-inline"></i></h5>
                        </label>
                        <div class="input-group">
                            <div type="number" class="form-control" required="" id="card-cvv"></div>
                        </div>
                    </div>
                    <div>
                        <div id="remember-card"></div>
                    </div>
                    <div class="card-footer">
                        <div class="credit-form">
                            <div class="row">
                                <div class="col-md-6">
                                    <?php echo Html::button('กลับ', ['class' => 'btn btn-warning btn-lg btn-block', 'onclick' => 'history.back(LoadingShow());']); ?>
                                </div>
                                <div class="col-md-6">
                                    <form method="POST" action="<?php echo Url::to(['payment/check-data-redirect']); ?>">
                                        <script src="https://dev-kpaymentgateway.kasikornbank.com/ui/v2/kinlinepayment.min.js" 
                                                data-apikey="<?php echo Yii::$app->params['publickey']; ?>" 
                                                data-lang="TH" 
                                                data-write-log="false">
                                        </script>
                                        <input type="hidden" name="_csrf" value="<?=Yii::$app->request->getCsrfToken()?>" />
                                        <input type="hidden" name="customerName" value="<?=$resultData['customer_name'];?>" />
                                        <input type="hidden" name="amount" value="<?=$resultData['amount'];?>" />
                                        <input type="hidden" name="textSms" value="<?=$resultData['text_sms'];?>" />
                                        <input type="hidden" name="sourceType" value="<?=$sourceType;?>" />
                                        <button class="btn btn-success btn-lg btn-block"> ยืนยัน (<?=number_format($resultData['amount'], 2);?>) </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

views/payment/_form-verify-send-sms.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

// \app\assets\PaymentAsset::register($this);
$this->title = 'ตรวจสอบการส่ง SMS';
// $this->params['breadcrumbs'][] = $this->title;
// echo '<pre>';
// print_r($resPayment);exit;
if ($resPayment['success']) {
    $bg = 'success';
} else {
    $bg = 'danger';
}
?>
<div class="payment-send-sms">
    <div class="container">
        <div class="row" style="margin-top: 5px;">
            <div class="col-sm-12">
                <div class="form-container">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">ตรวจสอบการส่ง SMS</h3>
                        </div>
                        <div class="panel-body">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-sm-12 text-center">
                                        <img src="<?php echo Yii::getAlias('@web'); ?>/img/payment/<?php echo $resPayment['icons']; ?>" width="90" height="90">
                                    </div>
                                </div>
                                <div class="row" style="margin-top: 10px;">
                                    <div class="col-sm-12 text-center">
                                        <div class="text-<?php echo $bg; ?>" style="font-size: 18px; font-weight: 600; font-margin: 0;"><?php echo empty($resPayment['message']) ? null : $resPayment['message']; ?></div>
                                    </div>
                                </div>
                                <div class="row justify-content-center">
                                    <div class="col-5 text-center">
                                        <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#detail-send-sms" aria-expanded="false"> แสดงรายละเอียด </button>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12">
                                        <div class="collapse" id="detail-send-sms">
                                            <?php echo $this->render('_content-info-send-sms', ['resRequest' => $resRequest, 'resFullUrl' => $resFullUrl, 'resShortUrl' => $resShortUrl, 'resPayment' => $resPayment]); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php if ($resPayment['success']) { //ถ้ายังไม่ส่งให้เปิดปุ่ม 
                        ?>
                            <div class="panel-footer text-center">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <?php echo Html::button('<i class="fa fa-paper-plane"></i> ส่ง SMS', ['class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin: 0px;', 'onclick' => 'sendSMS("' . $resRequest['customer_tel'] . '");']); ?>
                                    </div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(function(){
        $("input[class=swal2-input]").attr('disabled', true);
        // swal2-input
    });
    var baseUrl = "<?php echo Url::base(); ?>";

    function sendSMS(number) {
        var fnCheckNumber = phoneNumber(number);
        var fnCheckNumber = JSON.parse(fnCheckNumber);
        Swal.fire({
            icon: 'question',
            title: 'ต้องการส่ง SMS ใช่หรือไม่',
            // text: "เบอร์",
            showCancelButton: true,
            confirmButtonColor: '#00a65a',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ตกลง',
            cancelButtonText: 'ยกเลิก',
            showLoaderOnConfirm: true,
            allowOutsideClick: false,
            focusConfirm: false,
            inputValue: number,
            input: 'text',
            inputValidator: () => {
                return (!fnCheckNumber.success) && fnCheckNumber.message
            }
        }).then((result) => {
            if (result.value) {
                var resRequest = [];
                resRequest = JSON.parse('<?php echo json_encode($resRequest); ?>');
                resRequest['link_before_convert'] = '<?php echo $resFullUrl; ?>';
                resRequest['code_check'] = '<?php echo $resRequest['code_check']; ?>';
                resRequest['code_recheck'] = '<?php echo $resRequest['code_recheck']; ?>';
                // console.log(resRequest);return false;
                $.ajax({
                    url: baseUrl + '/payment/save-verify-send-sms',
                    type: 'get',
                    data: resRequest,
                    dataType: 'json',
                    beforeSend: function() {
                        LoadingShow();
                    },
                    success: function(data) {
                        console.log(data);
                        //บันทึกสำเร็จ
                        if (data.success) {
                            Swal.fire({
                                icon: 'success',
                                title: data.title + '<br><br>' + data.message,
                                confirmButtonColor: '#3085d6',
                                confirmButtonText: 'ปิด',
                                allowOutsideClick: false,
                                focusConfirm: false,
                            }).then((result) => {
                                Swal.fire({
                                    title: 'กำลังปิด',
                                    text: 'โปรดรอสักครู่...',
                                    timer: location.reload(),
                                    allowOutsideClick: false,
                                    focusConfirm: false,
                                    onOpen: () => {
                                        swal.showLoading();
                                    }
                                })
                            });
                            //ไม่สำเร็จ
                        } else {
                            Swal.fire({
                                title: data.title,
                                text: data.message,
                                icon: 'error',
                                confirmButtonColor: '#d33',
                                confirmButtonText: 'ปิด',
                                allowOutsideClick: false,
                                focusConfirm: false,
                            }).then((result) => {
                                Swal.fire({
                                    title: 'กำลังปิด',
                                    text: 'โปรดรอสักครู่...',
                                    timer: location.reload(),
                                    allowOutsideClick: false,
                                    focusConfirm: false,
                                    onOpen: () => {
                                        swal.showLoading();
                                    }
                                })
                            });
                        }
                    },
                    complete: function() {
                        LoadingHide();
                    },
                }).fail(function(error) {
                    Swal.fire({
                        icon: 'error',
                        title: 'เกิดข้อผิดพลาด กรุณาแจ้งผู้ดูแลระบบ (' + error.status + ')',
                        html: '<p>paymentSaveSendSMS :</p><p>' + error.responseText + '</p>',
                        confirmButtonColor: '#d33',
                        confirmButtonText: 'ปิด',
                        allowOutsideClick: false,
                        focusConfirm: false,
                    });
                });
            }
        });
    }
</script>